version: '3'
services: 
  embulk-orders:
    image: embulk
    container_name: orders_ext
    command: ["java", "-jar", "/embulk/embulk.jar", "run", "/input/orders.yml"]

  embulk-orders_detail:
    image: embulk
    container_name: order_detail_ext
    command: ["java", "-jar", "/embulk/embulk.jar", "run", "/input/order_details.yml"]
    
      